# Generated by Django 3.1.3 on 2020-11-10 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('file_name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='images/gallery/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
