# Generated by Django 3.1.3 on 2020-11-10 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201110_0527'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('header_image', models.URLField()),
                ('content', models.TextField()),
                ('slug', models.SlugField(blank=True, max_length=40, null=True)),
            ],
            options={
                'verbose_name': 'Artikel',
            },
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Galeri Gambar', 'verbose_name_plural': 'Galeri Gambar'},
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to='images/gallery/'),
        ),
    ]
