# Generated by Django 3.1.3 on 2020-11-13 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201110_0736'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourismPacket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': 'Paket Wisata',
                'verbose_name_plural': 'Paket Wisata',
            },
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Artikel', 'verbose_name_plural': 'Artikel'},
        ),
        migrations.AlterField(
            model_name='article',
            name='header_image',
            field=models.ImageField(upload_to='images/article/'),
        ),
    ]
