# Generated by Django 3.1.3 on 2020-11-19 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201113_0605'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TourismPacket',
            new_name='TourismPackage',
        ),
    ]
