# Generated by Django 3.1.3 on 2020-11-19 04:38

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201119_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourismpackage',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=0, default_currency='IDR', max_digits=10),
        ),
    ]
