# Generated by Django 3.1.3 on 2020-12-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20201211_0404'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Konten', 'verbose_name_plural': 'Konten'},
        ),
        migrations.AddField(
            model_name='article',
            name='qr_code',
            field=models.ImageField(default=None, upload_to='images/qr_code/'),
            preserve_default=False,
        ),
    ]
