# Generated by Django 3.1.3 on 2020-12-21 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20201221_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('header_image', models.ImageField(upload_to='images/content/')),
                ('content', models.TextField()),
                ('slug', models.SlugField(blank=True, max_length=40, null=True)),
                ('qr_code', models.ImageField(upload_to='images/content/')),
            ],
            options={
                'verbose_name': 'Konten',
                'verbose_name_plural': 'Konten',
            },
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
