# Generated by Django 3.1.3 on 2021-01-14 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210114_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='gallery_image_1',
            field=models.ImageField(default=None, upload_to='images/content/'),
        ),
        migrations.AlterField(
            model_name='content',
            name='gallery_image_2',
            field=models.ImageField(default=None, upload_to='images/content/'),
        ),
        migrations.AlterField(
            model_name='content',
            name='gallery_image_3',
            field=models.ImageField(default=None, upload_to='images/content/'),
        ),
    ]
