# Generated by Django 3.1.3 on 2021-02-03 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egg_report', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='is_lay_egg',
        ),
        migrations.AddField(
            model_name='report',
            name='egg',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
