# Generated by Django 3.1.3 on 2021-01-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egg_report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_lay_egg',
            field=models.BooleanField(default=False),
        ),
    ]
