# Generated by Django 3.1.3 on 2021-01-30 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('egg_report', '0005_auto_20210130_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cage',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='cage_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='egg_report.cage'),
        ),
    ]
